export default {
  default: ["barista"],
  front: [
    "studio ghibli portrait, soft rim light",
    "cyberpunk neon portrait 90s anime",
    "watercolor ink portrait, loose brush",
    "melting holographic portrait, liquid chrome",
    "psychedelic kaleidoscope face, fractal patterns",
    "glitch art portrait, RGB split, datamosh",
    "cosmic deity portrait, galaxy skin, star eyes",
    "retro VHS portrait, scan lines, 80s aesthetic",
    "paper cutout collage portrait, layered colors",
    "stained glass portrait, vivid shards",
    "oil painting portrait, thick impasto brushstrokes",
    "pixel art portrait, 8-bit retro gaming",
    "neon wireframe portrait, tron grid",
    "ukiyo-e woodblock print portrait, bold lines",
    "art nouveau portrait, flowing organic lines, ornate border",
    "charcoal sketch portrait, dramatic shadows, textured paper",
    "pop art portrait, bold colors, ben-day dots, warhol style",
    "renaissance oil painting portrait, chiaroscuro lighting",
    "surrealist portrait, melting features, dali inspired",
    "impressionist portrait, visible brushstrokes, monet style",
    "geometric cubist portrait, fragmented planes, picasso style",
    "art deco portrait, golden ratios, elegant symmetry",
    "abstract expressionist portrait, bold gestural marks",
    "gothic portrait, dark romanticism, dramatic lighting",
    "minimalist line art portrait, continuous line drawing",
    "baroque portrait, ornate details, dramatic composition",
    "futuristic android portrait, chrome finish, LED accents",
    "vintage tin type portrait, sepia tones, daguerreotype",
    "fantasy crystal portrait, gemstone skin, ethereal glow",
    "steampunk portrait, brass gears, victorian aesthetic",
    "tribal mask portrait, bold patterns, ceremonial paint",
    "graffiti street art portrait, spray paint drips, urban",
    "cel-shaded anime portrait, bold outlines, flat colors",
    "ethereal ghost portrait, translucent, wispy trails",
  ],
  back: [
    "vaporwave cityscape",
    "film noir scene, grainy",
    "isometric tech poster, bold shapes",
    "surreal dreamscape, melting clocks, floating objects",
    "synthwave sunset, retrowave grid, palm trees",
    "abstract expressionism, bold paint splatters",
    "underwater coral reef, bioluminescent creatures",
    "cyberpunk rain-soaked alley, neon signs",
    "mandala pattern landscape, sacred geometry",
    "vintage comic book scene, ben-day dots, pop art",
    "low poly geometric world, faceted 3D",
    "infrared photography, false color landscape",
    "street art graffiti wall, bold tags, spray paint",
    "M.C. Escher impossible architecture, tessellations",
    "aurora borealis sky, swirling northern lights",
    "ancient temple ruins, overgrown jungle, mystical atmosphere",
    "nebula space scene, swirling cosmic dust, stars",
    "dystopian wasteland, post-apocalyptic, rusted metal",
    "enchanted forest, glowing mushrooms, fairy lights",
    "steampunk clockwork city, brass mechanisms, steam",
    "crystal cave, glowing minerals, underground wonder",
    "floating islands, waterfalls into clouds, fantasy realm",
    "neon tokyo street, rain reflections, busy night",
    "desert mirage, heat waves, surreal oasis",
    "arctic ice palace, frozen architecture, blue tones",
    "volcanic landscape, lava flows, dramatic fire glow",
    "alien planet surface, strange flora, dual suns",
    "medieval castle, fog, dramatic moonlight",
    "carnival carousel, vintage lights, whimsical",
    "zen garden, raked sand patterns, minimalist peace",
    "art gallery, abstract paintings, modern interior",
    "futuristic laboratory, holographic displays, sci-fi tech",
    "enchanted library, floating books, magical atmosphere",
    "cherry blossom garden, pink petals falling, serene",
    "gothic cathedral interior, stained glass, divine rays",
  ]
} as const;
