export default {
  default: ["barista"],
  front: [
    "studio ghibli portrait, soft rim light",
    "cyberpunk neon portrait 90s anime",
    "watercolor ink portrait, loose brush",
    "melting holographic portrait, liquid chrome",
    "psychedelic kaleidoscope face, fractal patterns",
    "glitch art portrait, RGB split, datamosh",
    "cosmic deity portrait, galaxy skin, star eyes",
    "retro VHS portrait, scan lines, 80s aesthetic",
    "paper cutout collage portrait, layered colors",
    "stained glass portrait, vivid shards",
    "oil painting portrait, thick impasto brushstrokes",
    "pixel art portrait, 8-bit retro gaming",
    "neon wireframe portrait, tron grid",
    "ukiyo-e woodblock print portrait, bold lines",
    "art nouveau portrait, flowing organic lines, ornate border",
    "charcoal sketch portrait, dramatic shadows, textured paper",
    "pop art portrait, bold colors, ben-day dots, warhol style",
    "renaissance oil painting portrait, chiaroscuro lighting",
    "surrealist portrait, melting features, dali inspired",
    "impressionist portrait, visible brushstrokes, monet style",
    "geometric cubist portrait, fragmented planes, picasso style",
    "art deco portrait, golden ratios, elegant symmetry",
    "abstract expressionist portrait, bold gestural marks",
    "gothic portrait, dark romanticism, dramatic lighting",
    "minimalist line art portrait, continuous line drawing",
    "baroque portrait, ornate details, dramatic composition",
    "futuristic android portrait, chrome finish, LED accents",
    "vintage tin type portrait, sepia tones, daguerreotype",
    "fantasy crystal portrait, gemstone skin, ethereal glow",
    "steampunk portrait, brass gears, victorian aesthetic",
    "tribal mask portrait, bold patterns, ceremonial paint",
    "graffiti street art portrait, spray paint drips, urban",
    "cel-shaded anime portrait, bold outlines, flat colors",
    "ethereal ghost portrait, translucent, wispy trails",
    "bioluminescent jellyface portrait, glowing tendrils, abyssal hues",
    "liquid metal mirror portrait, mercury drips, reflective skin",
    "fractal bloom portrait, infinite petals, sacred geometry",
    "prismatic refraction portrait, crystal shards, light splitting",
    "inkblot rorschach portrait, symmetrical stains, psycho-trippy",
    "hologram ghost portrait, scanline shimmer, chromatic edges",
    "moss and fungus portrait, mycelium crown, forest spirit",
    "neon vapor portrait, foggy aura, club lighting",
    "cosmic ray portrait, aurora highlights, magnetosphere glow",
    "sandstorm stencil portrait, grain texture, desert gold",
    "glitter glitch portrait, pixel confetti, party noise",
    "infrared heatmap portrait, thermal gradients",
    "UV blacklight portrait, fluorescent paint splatter",
    "procedural wireframe portrait, topo lines, elevation map",
    "smoke sculpture portrait, shapeshifting wisps",
    "marble statue portrait, cracked patina, ancient future",
    "oil slick portrait, rainbow film, wet sheen",
    "sinewave distortion portrait, audio-reactive lines",
    "kaleidoscope mirrorball portrait, disco fractals",
    "sticker-bomb portrait, street collage, matte vinyl",
    "glyphic rune portrait, glowing sigils, occult tech",
    "celestial navigator portrait, star charts, astrolabe",
    "laser grid portrait, volumetric beams, fog",
    "paper maché portrait, handmade textures",
    "origami fold portrait, creased planes",
    "ceramic glaze portrait, crackle finish",
    "amber fossil portrait, trapped bubbles",
    "rain-soaked window portrait, bokeh streaks",
    "constellation portrait, star freckles",
    "melted candy portrait, saturated drips",
    "vortex swirl portrait, spiral galaxies",
    "static noise portrait, CRT fuzz",
    "liquid crystal portrait, LCD phase",
    "photocopy zine portrait, xerox grain",
    "chalkboard sketch portrait, dusty strokes",
    "pastel cloud portrait, cotton candy",
    "mirror shard portrait, fragmented reflections",
    "circuit board portrait, microchip veins",
    "solar flare portrait, coronal arcs",
    "auric field portrait, aura photography",
    "ink cloud portrait, aquarium plume",
    "magnetic ferrofluid portrait, spiky crown",
    "paper lantern portrait, warm glow",
    "neon sumi-e portrait, electric brush",
    "plasma globe portrait, lightning filaments",
    "photogram portrait, cameraless shadow shapes",
    "spray stencil portrait, alley wall",
    "sonic boomburst portrait, waveform halo",
    "fog glass portrait, finger streaks",
    "sapphire crystal portrait, facet sparkle",
    "opal fire portrait, shifting iridescence",
    "murmuration portrait, flock particles",
    "glacial ice portrait, trapped light",
    "aurora ink portrait, polar colors",
    "comet trail portrait, motion glow",
    "vapor bloom portrait, shader fog",
    "moire interference portrait, wavy patterns",
    "truchet tile portrait, generative maze",
    "polka pop portrait, oversized dots",
    "barcode glitch portrait, scan errors",
    "halftone swirl portrait, print offset",
    "anodized metal portrait, rainbow sheen",
    "bubble wrap portrait, embossed texture",
    "velvet noir portrait, soft matte",
    "latex shine portrait, specular highlights",
    "sugar crystal portrait, macro sparkle",
    "ink bleed portrait, newspaper soak",
    "pareidolia portrait, faces in clouds",
    "lissajous curve portrait, oscillograph lines",
    "dyson sphere portrait, mini suns",
    "nebula ink wash portrait, diluted cosmos",
    "quartz geode portrait, amethyst core",
    "biotech splice portrait, DNA helix glow",
    "glowstick rave portrait, saturated UV",
    "shattered glass portrait, refracted rainbow",
    "stormlight portrait, sheet lightning rim",
    "aurora veil portrait, silky sky",
    "tempera fresco portrait, wall texture",
    "piet-mondrian mask portrait, primary grid",
    "hieroglyph neon portrait, techno tomb",
    "petrichor rain portrait, wet asphalt bokeh",
    "x-ray film portrait, bones and wires",
    "lava lamp portrait, goo blobs",
    "cosmic foam portrait, sea of stars",
    "fractal flame portrait, chaos field",
    "spectrum smear portrait, painterly RGB",
    "soap bubble portrait, interference skin",
    "honeycomb portrait, hex lattice",
    "vapor marble portrait, smoky veins",
    "haze bloom portrait, soft glow",
    "magenta cyan split portrait, duotone",
    "anaglyph stereo portrait, red-cyan",
    "paper marbling portrait, ebru swirls",
    "sumi ink wash portrait, misty strokes",
    "neon hieratic portrait, priest of light",
    "mosspunk portrait, overgrown circuit",
    "holographic foil portrait, rainbow specular",
    "liquid rubber portrait, stretchy shine",
    "pixel bloom portrait, oversized voxels",
    "dreamcore portrait, liminal vibe",
    "Captain Cobalt, neon astronaut portrait, visor glow, cosmic grit",
    "Nyx the Neon Fox, synthwave portrait, luminous fur",
    "Oracle-9, cyborg seer portrait, third-eye HUD",
    "Moth Saint Lumen, bioluminescent wings, halo eclipse",
    "DJ Prismatica, hologram hair, prismatic beats",
    "Professor Circuit, steampunk monocle, brass filigree",
    "Astral Nomad Vega, starfreckled skin, comet braids",
    "Kite the Cloudwalker, wind-tossed scarf, sky glyphs",
    "Echo Mirage, glitch twin portrait, datastream tears",
    "Lady Kaleido, fractal crown, stained-glass gaze",
    "Seraph of Static, CRT halo, scanline smile",
    "Captain Riptide, liquid chrome jacket, ripple aura",
    "Nocturne Quartz, geode heart, crystal lashes",
    "Marrowbyte, skeletal android portrait, neon tendons",
    "Dr. Mycelia, fungus laurels, spore glow",
    "Zed Zenith, zero-g dancer portrait, vapor trails",
    "Aurora Weaver, ribbon lights, polar shimmer",
    "Glyphkeeper Rowan, runic freckles, ink aura",
    "Circuit Sphinx, golden PCB, riddled gaze",
    "Zephyr Bloom, petal mask, pollen sparks",
    "Orbitron, synth wizard portrait, levitating sigils",
    "Captain Tidepool, bioluminescent diver portrait, sea halo",
    "Cinder Seraph, ember eyes, ash veil",
    "Patchwork Poet, stitched colors, fabric aura",
    "Nova Courier, star-mail satchel, warp grin",
  ],
  back: [
    "vaporwave cityscape",
    "film noir scene, grainy",
    "isometric tech poster, bold shapes",
    "surreal dreamscape, melting clocks, floating objects",
    "synthwave sunset, retrowave grid, palm trees",
    "abstract expressionism, bold paint splatters",
    "underwater coral reef, bioluminescent creatures",
    "cyberpunk rain-soaked alley, neon signs",
    "mandala pattern landscape, sacred geometry",
    "vintage comic book scene, ben-day dots, pop art",
    "low poly geometric world, faceted 3D",
    "infrared photography, false color landscape",
    "street art graffiti wall, bold tags, spray paint",
    "M.C. Escher impossible architecture, tessellations",
    "aurora borealis sky, swirling northern lights",
    "ancient temple ruins, overgrown jungle, mystical atmosphere",
    "nebula space scene, swirling cosmic dust, stars",
    "dystopian wasteland, post-apocalyptic, rusted metal",
    "enchanted forest, glowing mushrooms, fairy lights",
    "steampunk clockwork city, brass mechanisms, steam",
    "crystal cave, glowing minerals, underground wonder",
    "floating islands, waterfalls into clouds, fantasy realm",
    "neon tokyo street, rain reflections, busy night",
    "desert mirage, heat waves, surreal oasis",
    "arctic ice palace, frozen architecture, blue tones",
    "volcanic landscape, lava flows, dramatic fire glow",
    "alien planet surface, strange flora, dual suns",
    "medieval castle, fog, dramatic moonlight",
    "carnival carousel, vintage lights, whimsical",
    "zen garden, raked sand patterns, minimalist peace",
    "art gallery, abstract paintings, modern interior",
    "futuristic laboratory, holographic displays, sci-fi tech",
    "enchanted library, floating books, magical atmosphere",
    "cherry blossom garden, pink petals falling, serene",
    "gothic cathedral interior, stained glass, divine rays",
    "infinite mirror canyon, recursive cliffs, impossible depth",
    "desert of glass dunes, prismatic sands, bending light",
    "bio-lum forest path, glowing spores, midnight mist",
    "chromatic storm over ocean, inverted lightning, rolling neon waves",
    "hanging gardens in zero-g, floating vines, dew orbs",
    "hypercolor mountain range, velvet fog, aurora veins",
    "moss cathedral, living walls, spore beams",
    "crystal lattice city, refracted sun, grid shadows",
    "time loop plaza, ghost trails, blurred clocktower",
    "neon stalactite cave, liquid light, shimmering pools",
    "levitating stones over marsh, mirrorwater, rings of ripple",
    "monochrome rain alley, single red neon, cinematic haze",
    "giant koi sky, clouds as water, temple rooftops",
    "fractal jungle canopy, golden ratio leaves, dizzying height",
    "void sea pier, stars as water, moon tide",
    "holographic dunes, shifting shaders, polygon wind",
    "cathedral of sound, visible waves, resonant arches",
    "sapphire glacier tunnel, inner glow, blue horizons",
    "tilted horizon salt flats, mirage towers, lens flare",
    "gilded fog valley, sunshafts, dust glitter",
    "storm of origami birds, paper sky, folded sun",
    "amber forest, fossil light, honey air",
    "digital mangrove, pixel leaves, voxel roots",
    "astro temple courtyard, comet tails, shrine lanterns",
    "rainbow monsoon over jungle, prism sheets, thunder bloom",
    "lava river promenade, ember snow, basalt bridges",
    "clockwork orchard, ticking fruit, brass branches",
    "floating library stacks, page gusts, ink clouds",
    "vaporwave mall atrium, pastel palm, marble grid",
    "magnetized sand storm, iron filings dance, aurora arcs",
    "biolum tidepools, alien starfish, teal glow",
    "painted desert sky, brushstroke clouds, canvas horizon",
    "aurora waterfall, silk light, crystalline mist",
    "redwood colonnade, misted sunbeams, moss carpet",
    "endless staircase plaza, escher angles, quiet echoes",
    "sleeping giant dunes, ribbed wind lines, violet dusk",
    "prism rain forest, spectral drizzle, neon undergrowth",
    "abandoned observatory, spinning constellations, open dome",
    "electrum stormplain, glitter static, black sand",
    "mirage market, floating stalls, chroma fabrics",
    "ghost carnival, silent rides, moonlit cotton candy",
    "sacred geometry meadow, glowing glyph stones",
    "tidal city, stilt houses, mirror sunset",
    "liquid chrome river, mercury bends, steely sky",
    "ink sea with paper boats, sumi waves, zen wind",
    "glitched skyline, data towers, scrolling billboards",
    "polar desert, diamond dust, sundog halos",
    "fog cathedral docks, ringing buoys, light shafts",
    "sunken arcade, coral joysticks, pixel fish",
    "volumetric light forest, godrays, floating dust",
    "mushroom megacity, cap canopies, spore rain",
    "astral train platform, tracks of starlight",
    "quantum garden, superposed petals, flicker bloom",
    "rose quartz canyon, soft glow, velvet shadows",
    "glass rainforest, crystal vines, refractive fog",
    "neon monolith field, humming stones, tracing arcs",
    "shifting labyrinth, living walls, slow pulse",
    "kaleidoscope skylight, tessellated clouds, mosaic sun",
    "sugar snowfall square, pastel flurries, candy lampposts",
    "sky river delta, floating boats, waterfall horizon",
    "ocean of flowers, tidal petals, bee aurora",
    "overgrown railway bridge, vines and sparks, golden hour",
    "rainbow ice cave, frozen prisms, crunch echo",
    "dream motel strip, vacancy halos, humming neon",
    "chromed forest, mirrored bark, infinite repeats",
    "electric lotus pond, arc fireflies, sapphire water",
    "sands with giant bones, fossil dunes, low sun",
    "ancient portal grove, stone rings, humming air",
    "paper lantern river, drifting lights, festival night",
    "iridescent tundra, oil-slick snow, violet wind",
    "giant wind chimes valley, singing metal, breeze trails",
    "city of bridges, tangled spans, fog abyss",
    "moon quarry, chalk cliffs, star dust",
    "emerald mine hall, gem veins, green haze",
    "cloud cliff monasteries, stairways through mist",
    "sunset over algae sea, neon plankton, slow tide",
    "magenta thunder desert, forks of light, heat ghosts",
    "bamboo mirror maze, flicker lanterns, footstep echoes",
    "opal storm coastline, jewel spray, thundering surf",
    "crystalline storm over ruins, light shards, silent streets",
    "biotech greenhouse, glass ribs, vines in code",
    "lantern festival over lake, fire trails, soft drums",
    "whale road in the sky, star whales, surf clouds",
    "thunderhead cathedral, anvil light, rolling echo",
    "river of clocks, melting hours, time eddies",
    "nebula orchard, fruit moons, cosmic breeze",
    "subway of shadows, ghost commuters, flicker ads",
    "cactus aurora plain, spined silhouettes, green curtains",
    "violet quarry lake, mirror calm, stone halos",
    "algae bloom canals, teal glow, gondola trails",
    "sunflower metropolis, facing the sun, golden grid",
    "meteor shower pier, streaking sky, hush water",
    "fogged glass canyon, soft edges, pale sun",
    "honeycomb desert, hex dunes, amber air",
    "floating cranes harbor, slow ballet, sodium lights",
    "staircase forest, steps instead of trunks, leaf rain",
    "prismatic hailstorm plaza, jeweled ice, rainbow spray",
    "silent wind farm, spinning halos, dusk purple",
    "coral cathedral, vaulted reef, fish stained glass",
    "aurora over ruins, spectral curtains, snow hush",
  ]
} as const;
